### ISSUE TITLE
imgui 2.0

### ISSUE THREAD

**Issue by einarf** [kfields/arcade-imgui#9]
A 2.0 release of imgui is now released. In addition we should think about supporting arcade 3.0.

So far it looks like you just need to upgrade the imgui version, but there might be more fancy stuff that needs updating? I can render the demo gui with no problems.

**Comment by kfields** [comment]
Thanks for bringing this up.  I upgraded it a couple of weeks ago but had not gotten around to pushing the changes.  Just did.
There was only some minor breakage in the demo which I fixed, the renderer is fine.
If you want to review or change anything let me know otherwise I'll just publish it at the end of the week I suppose.

I'll create an `arcade3` branch.  Sound good? :)
